### ISSUE TITLE
firebase: Unable to process request due to missing initial state in mobile browsers.

### ISSUE THREAD

**Issue by wajeshubham** [wajeshubham/snippng#13]
When trying to do sign with popup/redirect (social login: GitHub), user is getting the following error (working fine in incognito mode though 🥴):

`Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.`

There is no concrete resolution suggested by firebase on this yet. Find complete official thread regarding the same issue here: 

ISSUE: [https://github.com/firebase/firebase-js-sdk/issues/4256](https://github.com/firebase/firebase-js-sdk/issues/4256)

We may gradually move the auth service (low priority) to a custom server because Snippng is a developer-first application and the firebase issue only affected mobile browsers while working **perfectly** in desktop browsers and incognito mode.

If you have a solution for the problem, kindly share it in the comments; it would be very beneficial.

**Comment by wajeshubham** [comment]
Changed to Google authentication since it wasn't giving the above error. Still keeping an eye on the Firebase issue.

**Comment by KittichoteKamalapirat** [comment]
Did you manage to make the Github login work? I'm also facing the same issue. Have to only provide Google Login for now.
